version: '3.6'
services: 
  postgres:
    container_name: postgres
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=archway
      - POSTGRES_USER=archway
      - POSTGRES_PASSWORD=password
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./database/postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always