version: '3.6'
services: 
  postgres:
    container_name: postgres
    image: postgres:latest
    #command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=archway
      - POSTGRES_USER=archway
      - POSTGRES_PASSWORD=password
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./database/postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
  hasura:
    image: hasura/graphql-engine:v2.6.2
    ports:
    - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://archway:password@postgres:5432/archway
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://archway:password@postgres:5432/archway
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey